### ISSUE TITLE
Skills don't work as expected

### ISSUE THREAD

**Issue by Extector** [nickrobson/skillmmo#2]
**Describe the bug**
I can't craft the items provided by the skills even when I select that every single item craftable should appear when I don't have the items expected to craft them.

**Minecraft and Fabric version**
Minecraft 1.19.4
Fabric 0.14.9

**Config changes**
None

**Other mods installed**
All the mods installed in the txt file.
[Mod List.txt](https://github.com/nickrobson/skillmmo/files/11398994/Mod.List.txt)

**To reproduce**
1. Create a new world
2. Level up
3. Acquire:
    - 1 level in agriculture
    - 6 levels in building
    - 12 levels in combat
    - 12 levels in mining
    - 1 level in sorcery
    - 1 level in storage
    - 10 levels in survival
    
4. See that you can't build:
    - Beds
    - Diamond Sword
    - Slabs
    - Ladders
    - Fences
    - And so on...

**Expected behavior**
Expected to appear all the blocks and items that I can craft, but, none of them appeared to craft.

**Screenshots**
![image](https://user-images.githubusercontent.com/84629142/236256919-aa4a3f52-9c3f-48c6-97e0-5c3bfa26c978.png)
![image](https://user-images.githubusercontent.com/84629142/236257028-c1c40670-3a35-4ae0-87fa-4c3da0b6962d.png)
![image](https://user-images.githubusercontent.com/84629142/236257092-67677f9e-992d-4c28-8d78-d528a70c41ae.png)

**Comment by nickrobson** [comment]
Hey! Thanks again for raising this 😃 

For some of these, this is due to recipes (by default) being locked until you gain the items required to craft them:
- beds require wool, which requires Animal Husbandry 3
- diamond swords require Combat 15

For slabs, fences, and ladders... that's an interesting one. Based on your levels, you should be able to see the recipes for slabs (Building 1), ladders (Building 3), and fences (Building 5). The only thing I can think of is that Minecraft hasn't shown you the recipe yet because you haven't crafted a required block, but in your inventory I see you have sticks so I don't really understand why that wouldn't work 🤔  I set up a local version of Minecraft with each of the mods you sent, but I wasn't able to reproduce the issue after an hour of trying to 😢 .

Could you please maybe just try crafting planks and sticks again and see what happens, and just make sure you're level 6 in Building?

If not you can try `/recipe give @p minecraft:dark_oak_fence` and `/recipe give @p minecraft:dark_oak_slab` etc. to see if you can give yourself the recipe manually. If this says "No new recipes were learned" then it means the recipe is locked, if it says "Unlocked 1 recipes for ..." then it was a bug that it was locked and you now have the recipe.

---

In any case, if you want a workaround to this, you can set the `lockRecipesUntilIngredientsAndOutputAreUnlocked` config setting to `false` to show you all recipes (you don't need to quit the game to change the setting, just quit to the main menu, change the setting, save the file, and re-open your world). You could even try this and then change the setting back to `true` to see if the problem is fixed or starts again.

A quick way to see if a recipe is locked is to open a recipe using JEI and hover over the ingredients and crafting result. If either says (for example) "Locked - Building 5", then the recipe is locked.

**Comment by nickrobson** [comment]
The only other thing I can think of is if you have any datapacks installed that affect advancements or recipes, that could cause an issue with this, since the mod relies upon recipes being unlocked through advancements giving you the recipe for items. (Minecraft internally uses advancements to unlock new recipes, such as acquiring sticks is an advancement that unlocks the recipes for tools etc.)

If you still have problems with the recipe book being messed up and you can't craft something for some reason, you can disable the (vanilla) `doLimitedCrafting` game-rule which is used to disable crafting locked items, by using `/gamerule doLimitedCrafting false`. I'd only do this as a final thing to try. This and the config setting I mentioned above are the only ways that SkillMMO affects what can/can't be crafted.

**Comment by Extector** [comment]
Well, I tried everything and came to a conclusion...
The world is bugged 😢😢. As you said, trying to create again I also tried but it didn't work, no matter how much I created new materials. I imagine it's a bug due to the amount of mods. I created a new world and tested the features, which are working perfectly,

Thanks for the attention! 😊

**Comment by nickrobson** [comment]
Damn that sucks to hear.
I just want to confirm for my own knowledge, did you create the original world with the mod already or did you add the mod to the world after it was already created?
